### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by vitaly-zdanevich** [yejianye/eversync#2]
`eversync --dir ~/.local/share/notes/ --notebook 'xfce4-notes'`

```
Traceback (most recent call last):
  File "/usr/local/bin/eversync", line 9, in <module>
    load_entry_point('eversync==0.1.0', 'console_scripts', 'eversync')()
  File "build/bdist.linux-i686/egg/eversync/main.py", line 179, in main
  File "build/bdist.linux-i686/egg/eversync/main.py", line 136, in changed_since_last_sync
ValueError: max() arg is an empty sequence
```

**Comment by yejianye** [comment]
Looks like eversync didn't find any file with .txt, .md, markdown, .org under ~/.local/share/notes directory.

**Comment by vitaly-zdanevich** [comment]
Xubuntu have preinstalled simple note app `xfce4-notes` that stores plain text in files without any extensions - maybe you can fix your code for such situations?..

**Comment by yejianye** [comment]
A potential improvement for existing approach is to allow a `.eversync` file in which users could specify the file patterns that they want to include for syncing. 

An example of `.eversync` file 

```
*.txt
*.md
my-note
```

**Comment by vitaly-zdanevich** [comment]
I created file `.eversync` with the content: `my-note` in my folder with files for sync, but again I see the same error after
`eversync --dir /my/path/ --notebook 'my-notebook'`

![eversync-error](https://cloud.githubusercontent.com/assets/3514015/13035099/80d43fee-d358-11e5-9433-9d6182bf9b9b.png)
