### ISSUE TITLE
sync with org file failed with error Document is empty

### ISSUE THREAD

**Issue by linux-xhyang** [yejianye/eversync#3]
eversync --debug --force --dir ~/note --notebook gtd
Found notebook gtd
Found 61 note files under /home/xhyang/note
DEBUG: index.org is a new note file.
sh: printf: I/O error
Traceback (most recent call last):
  File "/usr/local/bin/eversync", line 9, in <module>
    load_entry_point('eversync==0.1.0', 'console_scripts', 'eversync')()
  File "build/bdist.linux-i686/egg/eversync/main.py", line 180, in main
  File "build/bdist.linux-i686/egg/eversync/main.py", line 157, in sync
  File "build/bdist.linux-i686/egg/eversync/main.py", line 124, in upsert_notes
  File "build/bdist.linux-i686/egg/eversync/main.py", line 82, in create_note
  File "build/bdist.linux-i686/egg/eversync/processor.py", line 41, in get_content
  File "build/bdist.linux-i686/egg/eversync/processor.py", line 102, in body
  File "build/bdist.linux-i686/egg/eversync/processor.py", line 77, in _org_ruby_convert
  File "/usr/lib/python2.7/dist-packages/lxml/html/clean.py", line 501, in clean_html
    doc = fromstring(html)
  File "/usr/lib/python2.7/dist-packages/lxml/html/__init__.py", line 725, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/lib/python2.7/dist-packages/lxml/html/**init**.py", line 616, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty

**Comment by yejianye** [comment]
Run the following command in your shell and check whether there's any errors

```
org-ruby /home/xhyang/note/index.org --translate html
```

**Comment by linux-xhyang** [comment]
run org-ruby /home/xhyang/note/index.org --translate html 
and there has no error output

**Comment by yejianye** [comment]
Does it output correct html in stdout ? And what's your org-ruby version?

linux-xhyang notifications@github.com于2016年10月31日周一 下午3:27写道：

**Comment by linux-xhyang** [comment]
org-ruby --version
0.9.12
